/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package executable;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import server.LoginServer;
import user.User;
import util.Validator;

/**
 *
 * @author David
 */
public class WatchEye extends JFrame {
    
    /**
     * Creates new form Fakebook
     */
    public WatchEye() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeScreen = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        btLogoff = new javax.swing.JButton();
        btGroups = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btBuddies = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        btProfile = new javax.swing.JButton();
        friendPanel = new javax.swing.JPanel();
        friendLabel1 = new javax.swing.JLabel();
        btFriend1 = new javax.swing.JButton();
        friendListLabel = new javax.swing.JLabel();
        friendRequestListLabel = new javax.swing.JLabel();
        blockedListLabel = new javax.swing.JLabel();
        btFriendOption1 = new javax.swing.JButton();
        frLabel1 = new javax.swing.JLabel();
        frNameLabel1 = new javax.swing.JLabel();
        btAccept1 = new javax.swing.JButton();
        btDecline1 = new javax.swing.JButton();
        blLabel1 = new javax.swing.JLabel();
        blNameLabel1 = new javax.swing.JLabel();
        btUnblock1 = new javax.swing.JButton();
        friendLabel2 = new javax.swing.JLabel();
        btFriend2 = new javax.swing.JButton();
        btFriendOption2 = new javax.swing.JButton();
        friendLabel3 = new javax.swing.JLabel();
        btFriend3 = new javax.swing.JButton();
        btFriendOption3 = new javax.swing.JButton();
        friendLabel4 = new javax.swing.JLabel();
        btFriend4 = new javax.swing.JButton();
        btFriendOption4 = new javax.swing.JButton();
        friendLabel5 = new javax.swing.JLabel();
        btFriend5 = new javax.swing.JButton();
        btFriendOption5 = new javax.swing.JButton();
        friendLabel6 = new javax.swing.JLabel();
        btFriend8 = new javax.swing.JButton();
        btFriendOption6 = new javax.swing.JButton();
        friendLabel7 = new javax.swing.JLabel();
        btFriend7 = new javax.swing.JButton();
        btFriendOption7 = new javax.swing.JButton();
        friendLabel8 = new javax.swing.JLabel();
        btFriendOption8 = new javax.swing.JButton();
        friendLabel9 = new javax.swing.JLabel();
        btFriend6 = new javax.swing.JButton();
        btFriend9 = new javax.swing.JButton();
        btFriendOption9 = new javax.swing.JButton();
        friendLabel10 = new javax.swing.JLabel();
        btFriend10 = new javax.swing.JButton();
        btFriendOption10 = new javax.swing.JButton();
        frLabel2 = new javax.swing.JLabel();
        frNameLabel2 = new javax.swing.JLabel();
        btAccept2 = new javax.swing.JButton();
        btDecline2 = new javax.swing.JButton();
        frLabel3 = new javax.swing.JLabel();
        frNameLabel3 = new javax.swing.JLabel();
        btAccept3 = new javax.swing.JButton();
        btDecline3 = new javax.swing.JButton();
        frLabel4 = new javax.swing.JLabel();
        frNameLabel4 = new javax.swing.JLabel();
        btAccept4 = new javax.swing.JButton();
        btDecline4 = new javax.swing.JButton();
        frLabel5 = new javax.swing.JLabel();
        frNameLabel5 = new javax.swing.JLabel();
        btAccept5 = new javax.swing.JButton();
        btDecline5 = new javax.swing.JButton();
        blLabel2 = new javax.swing.JLabel();
        blNameLabel2 = new javax.swing.JLabel();
        btUnblock2 = new javax.swing.JButton();
        blLabel3 = new javax.swing.JLabel();
        blNameLabel3 = new javax.swing.JLabel();
        btUnblock3 = new javax.swing.JButton();
        blLabel4 = new javax.swing.JLabel();
        blNameLabel4 = new javax.swing.JLabel();
        btUnblock4 = new javax.swing.JButton();
        blLabel5 = new javax.swing.JLabel();
        blNameLabel5 = new javax.swing.JLabel();
        btUnblock5 = new javax.swing.JButton();
        btFriendPrev = new javax.swing.JButton();
        btFriendNext = new javax.swing.JButton();
        btRequestPrev = new javax.swing.JButton();
        btRequestNext = new javax.swing.JButton();
        btBlockPrev = new javax.swing.JButton();
        btBlockNext = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();
        newFriendField = new javax.swing.JTextField();
        btSend = new javax.swing.JButton();
        loginScreen = new javax.swing.JPanel();
        welcomeLogo = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginMailLabel = new javax.swing.JLabel();
        loginMailField = new javax.swing.JTextField();
        loginPasslLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JPasswordField();
        btEnter = new javax.swing.JButton();
        btResetPassword = new javax.swing.JButton();
        btLoginRegister = new javax.swing.JButton();
        loginHeader = new javax.swing.JLabel();
        loginFootnote = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        regNameLabel = new javax.swing.JLabel();
        regNameField = new javax.swing.JTextField();
        regMailLabel = new javax.swing.JLabel();
        regMailField = new javax.swing.JTextField();
        regPassLabel = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();
        regGenderLabel = new javax.swing.JLabel();
        regGenderBox = new javax.swing.JComboBox<>();
        regDobLabel = new javax.swing.JLabel();
        ddBox = new javax.swing.JComboBox<>();
        mmBox = new javax.swing.JComboBox<>();
        yyyyBox = new javax.swing.JComboBox<>();
        tosCheckBox = new javax.swing.JCheckBox();
        btRegister = new javax.swing.JButton();
        regHeader = new javax.swing.JLabel();
        regFootnote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fakebook");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        homeScreen.setVisible(false);
        homeScreen.setEnabled(true);
        homeScreen.setBackground(new java.awt.Color(153, 153, 153));
        homeScreen.setPreferredSize(new java.awt.Dimension(0, 0));

        headerPanel.setBackground(new java.awt.Color(0, 153, 51));

        btLogoff.setText("Sair");
        btLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoffActionPerformed(evt);
            }
        });

        btGroups.setText("Grupos");

        jLabel2.setText("gpIcon");

        btBuddies.setText("Amigos");
        btBuddies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuddiesActionPerformed(evt);
            }
        });

        jLabel3.setText("bdIcon");

        btProfile.setText("btPerfil");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuddies, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogoff)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuddies, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        profileIcon.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));

        friendPanel.setEnabled(false);
        friendPanel.setVisible(false);
        friendPanel.setBackground(new java.awt.Color(204, 204, 0));
        friendPanel.setLayout(null);

        friendLabel1.setText("friendLabel1");
        friendLabel1.setVisible(false);
        friendPanel.add(friendLabel1);
        friendLabel1.setBounds(10, 61, 40, 40);

        btFriend1.setText("btFriend1");
        btFriend1.setEnabled(false);
        btFriend1.setVisible(false);
        friendPanel.add(btFriend1);
        btFriend1.setBounds(54, 61, 509, 40);

        friendListLabel.setText("Amigos");
        friendPanel.add(friendListLabel);
        friendListLabel.setBounds(10, 11, 620, 44);

        friendRequestListLabel.setText("Pedidos de Amizade");
        friendPanel.add(friendRequestListLabel);
        friendRequestListLabel.setBounds(640, 11, 310, 44);

        blockedListLabel.setText("Bloqueado");
        friendPanel.add(blockedListLabel);
        blockedListLabel.setBounds(960, 11, 310, 44);

        btFriendOption1.setText("btOption1");
        btFriendOption1.setVisible(false);
        btFriendOption1.setEnabled(false);
        btFriendOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption1ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption1);
        btFriendOption1.setBounds(569, 61, 61, 40);

        frLabel1.setText("friendIcon1");
        frLabel1.setVisible(false);
        friendPanel.add(frLabel1);
        frLabel1.setBounds(640, 61, 40, 40);

        frNameLabel1.setText("friendName1");
        frNameLabel1.setVisible(false);
        friendPanel.add(frNameLabel1);
        frNameLabel1.setBounds(686, 61, 264, 40);

        btAccept1.setText("Aceitar");
        btAccept1.setEnabled(false);
        btAccept1.setVisible(false);
        btAccept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccept1ActionPerformed(evt);
            }
        });
        friendPanel.add(btAccept1);
        btAccept1.setBounds(640, 107, 152, 40);

        btDecline1.setText("Recusar");
        btDecline1.setEnabled(false);
        btDecline1.setVisible(false);
        btDecline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecline1ActionPerformed(evt);
            }
        });
        friendPanel.add(btDecline1);
        btDecline1.setBounds(802, 107, 148, 40);

        blLabel1.setText("blockedIcon1");
        blLabel1.setVisible(false);
        friendPanel.add(blLabel1);
        blLabel1.setBounds(960, 61, 40, 40);

        blNameLabel1.setText("blockedName1");
        blNameLabel1.setVisible(false);
        friendPanel.add(blNameLabel1);
        blNameLabel1.setBounds(1006, 61, 264, 40);

        btUnblock1.setText("Desbloquear");
        btUnblock1.setEnabled(false);
        btUnblock1.setVisible(false);
        btUnblock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnblock1ActionPerformed(evt);
            }
        });
        friendPanel.add(btUnblock1);
        btUnblock1.setBounds(960, 107, 310, 40);

        friendLabel2.setText("friendLabel1");
        friendLabel2.setVisible(false);
        friendPanel.add(friendLabel2);
        friendLabel2.setBounds(10, 107, 40, 40);

        btFriend2.setText("btFriend1");
        btFriend2.setEnabled(false);
        btFriend2.setVisible(false);
        friendPanel.add(btFriend2);
        btFriend2.setBounds(54, 107, 509, 40);

        btFriendOption2.setText("btOption1");
        btFriendOption2.setVisible(false);
        btFriendOption2.setEnabled(false);
        btFriendOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption2ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption2);
        btFriendOption2.setBounds(569, 107, 61, 40);

        friendLabel3.setText("friendLabel1");
        friendLabel3.setVisible(false);
        friendPanel.add(friendLabel3);
        friendLabel3.setBounds(10, 153, 40, 40);

        btFriend3.setText("btFriend1");
        btFriend3.setEnabled(false);
        btFriend3.setVisible(false);
        friendPanel.add(btFriend3);
        btFriend3.setBounds(54, 153, 509, 40);

        btFriendOption3.setText("btOption1");
        btFriendOption3.setVisible(false);
        btFriendOption3.setEnabled(false);
        btFriendOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption3ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption3);
        btFriendOption3.setBounds(569, 153, 61, 40);

        friendLabel4.setText("friendLabel1");
        friendLabel4.setVisible(false);
        friendPanel.add(friendLabel4);
        friendLabel4.setBounds(10, 199, 40, 40);

        btFriend4.setText("btFriend1");
        btFriend4.setEnabled(false);
        btFriend4.setVisible(false);
        friendPanel.add(btFriend4);
        btFriend4.setBounds(54, 199, 509, 40);

        btFriendOption4.setText("btOption1");
        btFriendOption4.setVisible(false);
        btFriendOption4.setEnabled(false);
        btFriendOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption4ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption4);
        btFriendOption4.setBounds(569, 199, 61, 40);

        friendLabel5.setText("friendLabel1");
        friendLabel5.setVisible(false);
        friendPanel.add(friendLabel5);
        friendLabel5.setBounds(10, 245, 40, 40);

        btFriend5.setText("btFriend1");
        btFriend5.setEnabled(false);
        btFriend5.setVisible(false);
        friendPanel.add(btFriend5);
        btFriend5.setBounds(54, 245, 509, 40);

        btFriendOption5.setText("btOption1");
        btFriendOption5.setVisible(false);
        btFriendOption5.setEnabled(false);
        btFriendOption5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption5ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption5);
        btFriendOption5.setBounds(569, 245, 61, 40);

        friendLabel6.setText("friendLabel1");
        friendLabel6.setVisible(false);
        friendPanel.add(friendLabel6);
        friendLabel6.setBounds(10, 291, 40, 40);

        btFriend8.setText("btFriend1");
        btFriend8.setEnabled(false);
        btFriend8.setVisible(false);
        friendPanel.add(btFriend8);
        btFriend8.setBounds(54, 383, 509, 40);

        btFriendOption6.setText("btOption1");
        btFriendOption6.setVisible(false);
        btFriendOption6.setEnabled(false);
        btFriendOption6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption6ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption6);
        btFriendOption6.setBounds(569, 291, 61, 40);

        friendLabel7.setText("friendLabel1");
        friendLabel7.setVisible(false);
        friendPanel.add(friendLabel7);
        friendLabel7.setBounds(10, 337, 40, 40);

        btFriend7.setText("btFriend1");
        btFriend7.setEnabled(false);
        btFriend7.setVisible(false);
        friendPanel.add(btFriend7);
        btFriend7.setBounds(54, 337, 509, 40);

        btFriendOption7.setText("btOption1");
        btFriendOption7.setVisible(false);
        btFriendOption7.setEnabled(false);
        btFriendOption7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption7ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption7);
        btFriendOption7.setBounds(569, 337, 61, 40);

        friendLabel8.setText("friendLabel1");
        friendLabel8.setVisible(false);
        friendPanel.add(friendLabel8);
        friendLabel8.setBounds(10, 383, 40, 40);

        btFriendOption8.setText("btOption1");
        btFriendOption8.setVisible(false);
        btFriendOption8.setEnabled(false);
        btFriendOption8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption8ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption8);
        btFriendOption8.setBounds(569, 383, 61, 40);

        friendLabel9.setText("friendLabel1");
        friendLabel9.setVisible(false);
        friendPanel.add(friendLabel9);
        friendLabel9.setBounds(10, 429, 40, 40);

        btFriend6.setText("btFriend1");
        btFriend6.setEnabled(false);
        btFriend6.setVisible(false);
        friendPanel.add(btFriend6);
        btFriend6.setBounds(54, 291, 509, 40);

        btFriend9.setText("btFriend1");
        btFriend9.setEnabled(false);
        btFriend9.setVisible(false);
        friendPanel.add(btFriend9);
        btFriend9.setBounds(54, 429, 509, 40);

        btFriendOption9.setText("btOption1");
        btFriendOption9.setVisible(false);
        btFriendOption9.setEnabled(false);
        btFriendOption9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption9ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption9);
        btFriendOption9.setBounds(569, 429, 61, 40);

        friendLabel10.setText("friendLabel1");
        friendLabel10.setVisible(false);
        friendPanel.add(friendLabel10);
        friendLabel10.setBounds(10, 475, 40, 40);

        btFriend10.setText("btFriend1");
        btFriend10.setEnabled(false);
        btFriend10.setVisible(false);
        friendPanel.add(btFriend10);
        btFriend10.setBounds(54, 475, 509, 40);

        btFriendOption10.setText("btOption1");
        btFriendOption10.setVisible(false);
        btFriendOption10.setEnabled(false);
        btFriendOption10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFriendOption10ActionPerformed(evt);
            }
        });
        friendPanel.add(btFriendOption10);
        btFriendOption10.setBounds(569, 475, 61, 40);

        frLabel2.setText("friendIcon1");
        frLabel2.setVisible(false);
        friendPanel.add(frLabel2);
        frLabel2.setBounds(640, 153, 40, 40);

        frNameLabel2.setText("friendName1");
        frNameLabel2.setVisible(false);
        friendPanel.add(frNameLabel2);
        frNameLabel2.setBounds(686, 153, 264, 40);

        btAccept2.setText("Aceitar");
        btAccept2.setEnabled(false);
        btAccept2.setVisible(false);
        btAccept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccept2ActionPerformed(evt);
            }
        });
        friendPanel.add(btAccept2);
        btAccept2.setBounds(640, 199, 152, 40);

        btDecline2.setText("Recusar");
        btDecline2.setEnabled(false);
        btDecline2.setVisible(false);
        btDecline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecline2ActionPerformed(evt);
            }
        });
        friendPanel.add(btDecline2);
        btDecline2.setBounds(802, 199, 148, 40);

        frLabel3.setText("friendIcon1");
        frLabel3.setVisible(false);
        friendPanel.add(frLabel3);
        frLabel3.setBounds(640, 245, 40, 40);

        frNameLabel3.setText("friendName1");
        frNameLabel3.setVisible(false);
        friendPanel.add(frNameLabel3);
        frNameLabel3.setBounds(686, 245, 264, 40);

        btAccept3.setText("Aceitar");
        btAccept3.setEnabled(false);
        btAccept3.setVisible(false);
        btAccept3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccept3ActionPerformed(evt);
            }
        });
        friendPanel.add(btAccept3);
        btAccept3.setBounds(640, 291, 152, 40);

        btDecline3.setText("Recusar");
        btDecline3.setEnabled(false);
        btDecline3.setVisible(false);
        btDecline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecline3ActionPerformed(evt);
            }
        });
        friendPanel.add(btDecline3);
        btDecline3.setBounds(802, 291, 148, 40);

        frLabel4.setText("friendIcon1");
        frLabel4.setVisible(false);
        friendPanel.add(frLabel4);
        frLabel4.setBounds(640, 337, 40, 40);

        frNameLabel4.setText("friendName1");
        frNameLabel4.setVisible(false);
        friendPanel.add(frNameLabel4);
        frNameLabel4.setBounds(686, 337, 264, 40);

        btAccept4.setText("Aceitar");
        btAccept4.setEnabled(false);
        btAccept4.setVisible(false);
        btAccept4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccept4ActionPerformed(evt);
            }
        });
        friendPanel.add(btAccept4);
        btAccept4.setBounds(640, 383, 152, 40);

        btDecline4.setText("Recusar");
        btDecline4.setEnabled(false);
        btDecline4.setVisible(false);
        btDecline4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecline4ActionPerformed(evt);
            }
        });
        friendPanel.add(btDecline4);
        btDecline4.setBounds(802, 383, 148, 40);

        frLabel5.setText("friendIcon1");
        frLabel5.setVisible(false);
        friendPanel.add(frLabel5);
        frLabel5.setBounds(640, 429, 40, 40);

        frNameLabel5.setText("friendName1");
        frNameLabel5.setVisible(false);
        friendPanel.add(frNameLabel5);
        frNameLabel5.setBounds(686, 429, 264, 40);

        btAccept5.setText("Aceitar");
        btAccept5.setEnabled(false);
        btAccept5.setVisible(false);
        btAccept5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccept5ActionPerformed(evt);
            }
        });
        friendPanel.add(btAccept5);
        btAccept5.setBounds(640, 475, 152, 40);

        btDecline5.setText("Recusar");
        btDecline5.setEnabled(false);
        btDecline5.setVisible(false);
        btDecline5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecline5ActionPerformed(evt);
            }
        });
        friendPanel.add(btDecline5);
        btDecline5.setBounds(802, 475, 148, 40);

        blLabel2.setText("blockedIcon1");
        blLabel2.setVisible(false);
        friendPanel.add(blLabel2);
        blLabel2.setBounds(960, 153, 40, 40);

        blNameLabel2.setText("blockedName1");
        blNameLabel2.setVisible(false);
        friendPanel.add(blNameLabel2);
        blNameLabel2.setBounds(1006, 153, 264, 40);

        btUnblock2.setText("Desbloquear");
        btUnblock2.setEnabled(false);
        btUnblock2.setVisible(false);
        btUnblock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnblock2ActionPerformed(evt);
            }
        });
        friendPanel.add(btUnblock2);
        btUnblock2.setBounds(960, 199, 310, 40);

        blLabel3.setText("blockedIcon1");
        blLabel3.setVisible(false);
        friendPanel.add(blLabel3);
        blLabel3.setBounds(960, 245, 40, 40);

        blNameLabel3.setText("blockedName1");
        blNameLabel3.setVisible(false);
        friendPanel.add(blNameLabel3);
        blNameLabel3.setBounds(1006, 245, 264, 40);

        btUnblock3.setText("Desbloquear");
        btUnblock3.setEnabled(false);
        btUnblock3.setVisible(false);
        btUnblock3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnblock3ActionPerformed(evt);
            }
        });
        friendPanel.add(btUnblock3);
        btUnblock3.setBounds(960, 291, 310, 40);

        blLabel4.setText("blockedIcon1");
        blLabel4.setVisible(false);
        friendPanel.add(blLabel4);
        blLabel4.setBounds(960, 337, 40, 40);

        blNameLabel4.setText("blockedName1");
        blNameLabel4.setVisible(false);
        friendPanel.add(blNameLabel4);
        blNameLabel4.setBounds(1006, 337, 264, 40);

        btUnblock4.setText("Desbloquear");
        btUnblock4.setEnabled(false);
        btUnblock4.setVisible(false);
        btUnblock4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnblock4ActionPerformed(evt);
            }
        });
        friendPanel.add(btUnblock4);
        btUnblock4.setBounds(960, 383, 310, 40);

        blLabel5.setText("blockedIcon1");
        blLabel5.setVisible(false);
        friendPanel.add(blLabel5);
        blLabel5.setBounds(960, 429, 40, 40);

        blNameLabel5.setText("blockedName1");
        blNameLabel5.setVisible(false);
        friendPanel.add(blNameLabel5);
        blNameLabel5.setBounds(1006, 429, 264, 40);

        btUnblock5.setText("Desbloquear");
        btUnblock5.setEnabled(false);
        btUnblock5.setVisible(false);
        btUnblock5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnblock5ActionPerformed(evt);
            }
        });
        friendPanel.add(btUnblock5);
        btUnblock5.setBounds(960, 475, 310, 40);

        btFriendPrev.setText("Anterior");
        btFriendPrev.setVisible(false);
        btFriendPrev.setVisible(false);
        friendPanel.add(btFriendPrev);
        btFriendPrev.setBounds(54, 521, 252, 40);

        btFriendNext.setText("Próximo");
        btFriendNext.setVisible(false);
        btFriendNext.setEnabled(false);
        friendPanel.add(btFriendNext);
        btFriendNext.setBounds(312, 521, 251, 40);

        btRequestPrev.setText("Anterior");
        btRequestPrev.setVisible(false);
        btRequestPrev.setEnabled(false);
        friendPanel.add(btRequestPrev);
        btRequestPrev.setBounds(640, 521, 152, 40);

        btRequestNext.setText("Próximo");
        btRequestNext.setVisible(false);
        btRequestNext.setEnabled(false);
        friendPanel.add(btRequestNext);
        btRequestNext.setBounds(802, 521, 148, 40);

        btBlockPrev.setText("Anterior");
        btBlockPrev.setVisible(false);
        btBlockPrev.setEnabled(false);
        friendPanel.add(btBlockPrev);
        btBlockPrev.setBounds(960, 521, 152, 40);

        btBlockNext.setText("Próximo");
        btBlockNext.setVisible(false);
        btBlockNext.setEnabled(false);
        friendPanel.add(btBlockNext);
        btBlockNext.setBounds(1122, 521, 148, 40);

        btReturn.setText("Retornar");
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });
        friendPanel.add(btReturn);
        btReturn.setBounds(1122, 579, 148, 40);

        newFriendField.setText("Pesquisar amigo para adicionar...");
        newFriendField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newFriendFieldMouseClicked(evt);
            }
        });
        friendPanel.add(newFriendField);
        newFriendField.setBounds(54, 579, 509, 40);

        btSend.setText("btSend");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });
        friendPanel.add(btSend);
        btSend.setBounds(569, 579, 61, 40);

        javax.swing.GroupLayout homeScreenLayout = new javax.swing.GroupLayout(homeScreen);
        homeScreen.setLayout(homeScreenLayout);
        homeScreenLayout.setHorizontalGroup(
            homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeScreenLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(friendPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeScreenLayout.setVerticalGroup(
            homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeScreenLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friendPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );

        registerPanel.setVisible(false);
        registerPanel.setEnabled(false);
        loginScreen.setLayout(null);

        welcomeLogo.setBackground(new java.awt.Color(204, 204, 0));
        welcomeLogo.setText("logo");
        welcomeLogo.setOpaque(true);
        loginScreen.add(welcomeLogo);
        welcomeLogo.setBounds(0, 0, 1280, 220);

        loginPanel.setBackground(new java.awt.Color(0, 153, 153));

        loginMailLabel.setText("E-mail");

        loginMailField.setToolTipText("Seu e-mail cadastrado");

        loginPasslLabel.setText("Senha");

        loginPasswordField.setToolTipText("Sua senha cadastrada");

        btEnter.setText("Entrar");
        btEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnterActionPerformed(evt);
            }
        });

        btResetPassword.setText("Esqueci minha senha");

        btLoginRegister.setText("Registrar-se");
        btLoginRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginRegisterActionPerformed(evt);
            }
        });

        loginHeader.setText("cabeçalho");

        loginFootnote.setText("rodapé");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginPasslLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginPasswordField))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginMailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loginMailField, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btResetPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLoginRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(319, 319, 319))
            .addComponent(loginFootnote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(loginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginMailField, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(loginMailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPasslLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(loginPasswordField))
                .addGap(18, 18, 18)
                .addComponent(btEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btLoginRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginFootnote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginScreen.add(loginPanel);
        loginPanel.setBounds(0, 218, 1280, 500);

        registerPanel.setBackground(new java.awt.Color(0, 153, 153));

        regNameLabel.setLabelFor(regNameField);
        regNameLabel.setText("Nome");

        regNameField.setToolTipText("Seu Nome");

        regMailLabel.setText("E-mail");

        regMailField.setToolTipText("Seu Email");

        regPassLabel.setText("Senha");

        regPasswordField.setToolTipText("Sua senha, ela deve conter no mínimo 6 caracteres.");

        regGenderLabel.setText("Gênero");
        regGenderLabel.setToolTipText("");

        regGenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não sei" }));

        regDobLabel.setText("Data de Nascimento");

        ddBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ddBox.setToolTipText("");

        mmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yyyyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));

        tosCheckBox.setText("Li e concordo com os Termos de Uso e Política de Privacidade. ");

        btRegister.setText("Registrar-se");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        regHeader.setText("cabeçalho");

        regFootnote.setText("rodapé");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(655, 655, 655)
                        .addComponent(regGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(regGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(regPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(regMailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(regNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(regMailField, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                        .addComponent(regPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)))
                                .addGap(30, 30, 30)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addComponent(regDobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ddBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yyyyBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(tosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(96, 96, 96))
            .addComponent(regHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(regFootnote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(regHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regMailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(regMailField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(regDobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yyyyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(regPasswordField)
                    .addComponent(tosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regFootnote, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        loginScreen.add(registerPanel);
        registerPanel.setBounds(0, 218, 1280, 502);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(homeScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(homeScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginRegisterActionPerformed
        loginPanel.setVisible(false);
        loginPanel.setEnabled(false);
        if(!loginMailField.getText().trim().equals("")){
            regMailField.setText(loginMailField.getText());
        }
        registerPanel.setVisible(true);
        registerPanel.setEnabled(true);
    }//GEN-LAST:event_btLoginRegisterActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        User newUser;
        if(regNameField.getText().trim().equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "O nome está vazio!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(!Validator.validateName(regNameField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "O nome não é válido", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(regMailField.getText().trim().equals("")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "O e-mail está vazio!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(!Validator.validateEmail(regMailField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "O e-mail não é válido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(LoginServer.getInstance().emailInUse(regMailField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "O e-mail já está em uso!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(regPasswordField.getPassword().length < 6){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "A senha deve conter pelo menos 6 caracteres!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(!tosCheckBox.isSelected()){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "Você deve concordar com os Termos de Serviço e Política de Privacidade para Criar um Conta!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(!Validator.validateDate(ddBox.getSelectedItem() +"-"+ mmBox.getSelectedItem() +"-" + yyyyBox.getSelectedItem())){
             Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(loginScreen, "A data de nascimento não é válida!", "Aviso", JOptionPane.WARNING_MESSAGE);  
        } else {
            newUser = new User(regNameField.getText(), regMailField.getText(), new String(regPasswordField.getPassword()), regGenderBox.getSelectedIndex(), ddBox.getSelectedItem() +"-"+ mmBox.getSelectedItem() +"-" + yyyyBox.getSelectedItem());
            newUser.serialize();
            LoginServer.getInstance().addUser(newUser);
            LoginServer.getInstance().login(newUser);
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Toolkit.getDefaultToolkit().beep();
        int confirm = JOptionPane.showConfirmDialog(loginScreen.isVisible()? loginScreen : homeScreen, "Você deseja mesmo Sair?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            LoginServer.getInstance().shutdown();
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnterActionPerformed
        LoginServer.getInstance().enter(loginMailField.getText(), new String(loginPasswordField.getPassword()));
    }//GEN-LAST:event_btEnterActionPerformed

    private void btLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoffActionPerformed
        Toolkit.getDefaultToolkit().beep();
        int confirm = JOptionPane.showConfirmDialog(homeScreen, "Você deseja mesmo Sair?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0) {
            loginScreen.setVisible(true);
            loginScreen.setEnabled(true);
            homeScreen.setVisible(false);
            homeScreen.setEnabled(false);
            loginPanel.setVisible(true);
            loginPanel.setEnabled(true);
            newFriendField.setText(Constants.DEFAULT_NEW_FRIEND_TEXT);
            LoginServer.getInstance().logoff();
        }
    }//GEN-LAST:event_btLogoffActionPerformed

    private void btBuddiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuddiesActionPerformed
        friendPanel.setVisible(true);
        friendPanel.setEnabled(true);
        updateAndListFriendPanel(LoginServer.getInstance().getCurrentUser());
    }//GEN-LAST:event_btBuddiesActionPerformed

    private void newFriendFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newFriendFieldMouseClicked
        newFriendField.setText("");
    }//GEN-LAST:event_newFriendFieldMouseClicked

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        if(newFriendField.getText().equals(LoginServer.getInstance().getCurrentUser().getMail())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Você já é amigo de si mesmo! (Ou não)", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if(!LoginServer.getInstance().emailInUse(newFriendField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "O usuário não existe!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if(LoginServer.getInstance().blockedByReceiver(newFriendField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "O usuário lhe bloqueoou!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if(LoginServer.getInstance().getCurrentUser().isFriend(newFriendField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "O usuário já é seu amigo(a)!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if(LoginServer.getInstance().getCurrentUser().isDuplicateRequest(newFriendField.getText())){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Você possui um pedido pendente com este usuário!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            LoginServer.getInstance().addNewFriendRequest(newFriendField.getText(), LoginServer.getInstance().getCurrentUser());
            JOptionPane.showMessageDialog(this, "Pedido Enviado!", "Pedido de Amizade", JOptionPane.INFORMATION_MESSAGE);
        }
        newFriendField.setText(Constants.DEFAULT_NEW_FRIEND_TEXT);
    }//GEN-LAST:event_btSendActionPerformed

    private void btAccept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccept1ActionPerformed
        LoginServer.getInstance().friendRequestResponse(0, true);
    }//GEN-LAST:event_btAccept1ActionPerformed

    private void btAccept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccept2ActionPerformed
        LoginServer.getInstance().friendRequestResponse(1, true);
    }//GEN-LAST:event_btAccept2ActionPerformed

    private void btAccept3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccept3ActionPerformed
        LoginServer.getInstance().friendRequestResponse(2, true);
    }//GEN-LAST:event_btAccept3ActionPerformed

    private void btAccept4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccept4ActionPerformed
        LoginServer.getInstance().friendRequestResponse(3, true);
    }//GEN-LAST:event_btAccept4ActionPerformed

    private void btAccept5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccept5ActionPerformed
        LoginServer.getInstance().friendRequestResponse(4, true);
    }//GEN-LAST:event_btAccept5ActionPerformed

    private void btDecline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecline1ActionPerformed
        LoginServer.getInstance().friendRequestResponse(0, false);
    }//GEN-LAST:event_btDecline1ActionPerformed

    private void btDecline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecline2ActionPerformed
        LoginServer.getInstance().friendRequestResponse(1, false);
    }//GEN-LAST:event_btDecline2ActionPerformed

    private void btDecline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecline3ActionPerformed
        LoginServer.getInstance().friendRequestResponse(2, false);
    }//GEN-LAST:event_btDecline3ActionPerformed

    private void btDecline4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecline4ActionPerformed
        LoginServer.getInstance().friendRequestResponse(3, false);
    }//GEN-LAST:event_btDecline4ActionPerformed

    private void btDecline5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecline5ActionPerformed
        LoginServer.getInstance().friendRequestResponse(4, false);
    }//GEN-LAST:event_btDecline5ActionPerformed

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        friendPanel.setVisible(false);
        friendPanel.setEnabled(false);
    }//GEN-LAST:event_btReturnActionPerformed

    private void btFriendOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption1ActionPerformed
        showFriendOption(0);
    }//GEN-LAST:event_btFriendOption1ActionPerformed

    private void btFriendOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption2ActionPerformed
        showFriendOption(1);
    }//GEN-LAST:event_btFriendOption2ActionPerformed

    private void btFriendOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption3ActionPerformed
        showFriendOption(2);
    }//GEN-LAST:event_btFriendOption3ActionPerformed

    private void btFriendOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption4ActionPerformed
        showFriendOption(3);
    }//GEN-LAST:event_btFriendOption4ActionPerformed

    private void btFriendOption5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption5ActionPerformed
        showFriendOption(4);
    }//GEN-LAST:event_btFriendOption5ActionPerformed

    private void btFriendOption6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption6ActionPerformed
        showFriendOption(5);
    }//GEN-LAST:event_btFriendOption6ActionPerformed

    private void btFriendOption7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption7ActionPerformed
        showFriendOption(6);
    }//GEN-LAST:event_btFriendOption7ActionPerformed

    private void btFriendOption8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption8ActionPerformed
        showFriendOption(7);
    }//GEN-LAST:event_btFriendOption8ActionPerformed

    private void btFriendOption9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption9ActionPerformed
        showFriendOption(8);
    }//GEN-LAST:event_btFriendOption9ActionPerformed

    private void btFriendOption10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFriendOption10ActionPerformed
        showFriendOption(9);
    }//GEN-LAST:event_btFriendOption10ActionPerformed

    private void btUnblock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnblock1ActionPerformed
        LoginServer.getInstance().unblock(0);
    }//GEN-LAST:event_btUnblock1ActionPerformed

    private void btUnblock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnblock2ActionPerformed
        LoginServer.getInstance().unblock(1);
    }//GEN-LAST:event_btUnblock2ActionPerformed

    private void btUnblock3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnblock3ActionPerformed
        LoginServer.getInstance().unblock(2);
    }//GEN-LAST:event_btUnblock3ActionPerformed

    private void btUnblock4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnblock4ActionPerformed
        LoginServer.getInstance().unblock(3);
    }//GEN-LAST:event_btUnblock4ActionPerformed

    private void btUnblock5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnblock5ActionPerformed
        LoginServer.getInstance().unblock(4);
    }//GEN-LAST:event_btUnblock5ActionPerformed

    public void showFriendOption(int id){
        Toolkit.getDefaultToolkit().beep();
        String[] options = {"Bloquear", "Remover", "Cancelar"};
        int selection = JOptionPane.showOptionDialog(this, "O que deseja Fazer?", "Opções de Amizade", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        switch(selection){
            case 0:
                LoginServer.getInstance().removeFriend(id, true);
                break;
            case 1:
                LoginServer.getInstance().removeFriend(id, false);
                break;               
        }
    }
    
    public void welcome(User user){
        btProfile.setText(user.getName());
        if(user.getFriendRequestList().size() > 0){
            btBuddies.setText(Constants.BT_BUDDIES_TEXT + " (" + user.getFriendRequestList().size() + ")");
        } else {
            btBuddies.setText(Constants.BT_BUDDIES_TEXT);
        }
        homeScreen.setVisible(true);
        homeScreen.setEnabled(true);
        friendPanel.setVisible(false);
        friendPanel.setEnabled(false);
        if(loginScreen.isVisible()){
            loginScreen.setVisible(false);
            loginScreen.setEnabled(false);
            if(registerPanel.isVisible()){
                registerPanel.setVisible(false);
                registerPanel.setEnabled(false);
            }
            loginPanel.setVisible(false);
            loginPanel.setEnabled(false);
        }
    }
    
    private void listFriendRequest(User toList){
        if(toList.getFriendRequestList().size() < 5){
            updateFriendRequestList(toList.getFriendRequestList().size());
        }
        int i = 0;
        Iterator<User> it = toList.getFriendRequestList().iterator();
        while(it.hasNext() && i < 5){
            User requester = it.next();
            switch(i){
               case 0:
                    frLabel1.setVisible(true);
                    frLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    frNameLabel1.setVisible(true);
                    frNameLabel1.setText(requester.getName());
                    btAccept1.setVisible(true);
                    btAccept1.setEnabled(true);
                    btDecline1.setVisible(true);
                    btDecline1.setEnabled(true);
                    break;
                case 1:
                    frLabel2.setVisible(true);
                    frLabel2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    frNameLabel2.setVisible(true);
                    frNameLabel2.setText(requester.getName());
                    btAccept2.setVisible(true);
                    btAccept2.setEnabled(true);
                    btDecline2.setVisible(true);
                    btDecline2.setEnabled(true);
                    break;
                case 2:
                    frLabel3.setVisible(true);
                    frLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    frNameLabel3.setVisible(true);
                    frNameLabel3.setText(requester.getName());
                    btAccept3.setVisible(true);
                    btAccept3.setEnabled(true);
                    btDecline3.setVisible(true);
                    btDecline3.setEnabled(true);
                    break;
                case 3:
                    frLabel4.setVisible(true);
                    frLabel4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    frNameLabel4.setVisible(true);
                    frNameLabel4.setText(requester.getName());
                    btAccept4.setVisible(true);
                    btAccept4.setEnabled(true);
                    btDecline4.setVisible(true);
                    btDecline4.setEnabled(true);
                    break;
                case 4:
                    frLabel5.setVisible(true);
                    frLabel5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    frNameLabel5.setVisible(true);
                    frNameLabel5.setText(requester.getName());
                    btAccept5.setVisible(true);
                    btAccept5.setEnabled(true);
                    btDecline5.setVisible(true);
                    btDecline5.setEnabled(true);
                    break;
            }
            i++;
        }
    }
    
    private void updateFriendRequestList(int size){
        switch(size){
            case 0:
                frLabel1.setVisible(false);
                frNameLabel1.setVisible(false);
                btAccept1.setVisible(false);
                btAccept1.setEnabled(false);
                btDecline1.setVisible(false);
                btDecline1.setEnabled(false);
            case 1:
                frLabel2.setVisible(false);
                frNameLabel2.setVisible(false);
                btAccept2.setVisible(false);
                btAccept2.setEnabled(false);
                btDecline2.setVisible(false);
                btDecline2.setEnabled(false);
            case 2:
                frLabel3.setVisible(false);
                frNameLabel3.setVisible(false);
                btAccept3.setVisible(false);
                btAccept3.setEnabled(false);
                btDecline3.setVisible(false);
                btDecline3.setEnabled(false);
            case 3:
                frLabel4.setVisible(false);
                frNameLabel4.setVisible(false);
                btAccept4.setVisible(false);
                btAccept4.setEnabled(false);
                btDecline4.setVisible(false);
                btDecline4.setEnabled(false);
            case 4:
                frLabel5.setVisible(false);
                frNameLabel5.setVisible(false);
                btAccept5.setVisible(false);
                btAccept5.setEnabled(false);
                btDecline5.setVisible(false);
                btDecline5.setEnabled(false);
                break;
        }
    }
    
    private void listFriend(User toList){
        if(toList.getFriendList().size() < 10){
            updateFriendList(toList.getFriendList().size());
        }
        int i = 0;
        Iterator<User> it = toList.getFriendList().iterator();
        while(it.hasNext() && i < 10){
            User friend = it.next();
            switch(i){
               case 0:
                    friendLabel1.setVisible(true);
                    friendLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend1.setVisible(true);
                    btFriend1.setEnabled(true);
                    btFriend1.setText(friend.getName());
                    btFriendOption1.setVisible(true);
                    btFriendOption1.setEnabled(true);
                    break;
                case 1:
                    friendLabel2.setVisible(true);
                    friendLabel2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend2.setVisible(true);
                    btFriend2.setEnabled(true);
                    btFriend2.setText(friend.getName());
                    btFriendOption2.setVisible(true);
                    btFriendOption2.setEnabled(true);
                    break;
                case 2:
                    friendLabel3.setVisible(true);
                    friendLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend3.setVisible(true);
                    btFriend3.setEnabled(true);
                    btFriend3.setText(friend.getName());
                    btFriendOption3.setVisible(true);
                    btFriendOption3.setEnabled(true);
                    break;
                case 3:
                    friendLabel4.setVisible(true);
                    friendLabel4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend4.setVisible(true);
                    btFriend4.setEnabled(true);
                    btFriend4.setText(friend.getName());
                    btFriendOption4.setVisible(true);
                    btFriendOption4.setEnabled(true);
                    break;
                case 4:
                    friendLabel5.setVisible(true);
                    friendLabel5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend5.setVisible(true);
                    btFriend5.setEnabled(true);
                    btFriend5.setText(friend.getName());
                    btFriendOption5.setVisible(true);
                    btFriendOption5.setEnabled(true);
                    break;
                case 5:
                    friendLabel6.setVisible(true);
                    friendLabel6.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend6.setVisible(true);
                    btFriend6.setEnabled(true);
                    btFriend6.setText(friend.getName());
                    btFriendOption6.setVisible(true);
                    btFriendOption6.setEnabled(true);
                    break;
                case 6:
                    friendLabel7.setVisible(true);
                    friendLabel7.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend7.setVisible(true);
                    btFriend7.setEnabled(true);
                    btFriend7.setText(friend.getName());
                    btFriendOption7.setVisible(true);
                    btFriendOption7.setEnabled(true);
                    break;
                case 7:
                    friendLabel8.setVisible(true);
                    friendLabel8.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend8.setVisible(true);
                    btFriend8.setEnabled(true);
                    btFriend8.setText(friend.getName());
                    btFriendOption8.setVisible(true);
                    btFriendOption8.setEnabled(true);
                    break;
                case 8:
                    friendLabel9.setVisible(true);
                    friendLabel9.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend9.setVisible(true);
                    btFriend9.setEnabled(true);
                    btFriend9.setText(friend.getName());
                    btFriendOption9.setVisible(true);
                    btFriendOption9.setEnabled(true);
                    break;
                case 9:
                    friendLabel10.setVisible(true);
                    friendLabel10.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    btFriend10.setVisible(true);
                    btFriend10.setEnabled(true);
                    btFriend10.setText(friend.getName());
                    btFriendOption10.setVisible(true);
                    btFriendOption10.setEnabled(true);
                    break;
            }
            i++;
        } 
    }
    
    private void updateFriendList(int size){
        switch(size){
            case 0:
                friendLabel1.setVisible(false);
                btFriend1.setVisible(false);
                btFriend1.setEnabled(false);
                btFriendOption1.setVisible(false);
                btFriendOption1.setEnabled(false);
            case 1:
                friendLabel2.setVisible(false);
                btFriend2.setVisible(false);
                btFriend2.setEnabled(false);
                btFriendOption2.setVisible(false);
                btFriendOption2.setEnabled(false);
            case 2:
                friendLabel3.setVisible(false);
                btFriend3.setVisible(false);
                btFriend3.setEnabled(false);
                btFriendOption3.setVisible(false);
                btFriendOption3.setEnabled(false);
            case 3:
                friendLabel4.setVisible(false);
                btFriend4.setVisible(false);
                btFriend4.setEnabled(false);
                btFriendOption4.setVisible(false);
                btFriendOption4.setEnabled(false);
            case 4:
                friendLabel5.setVisible(false);
                btFriend5.setVisible(false);
                btFriend5.setEnabled(false);
                btFriendOption5.setVisible(false);
                btFriendOption5.setEnabled(false);
            case 5:
                friendLabel6.setVisible(false);
                btFriend6.setVisible(false);
                btFriend6.setEnabled(false);
                btFriendOption6.setVisible(false);
                btFriendOption6.setEnabled(false);
            case 6:
                friendLabel7.setVisible(false);
                btFriend7.setVisible(false);
                btFriend7.setEnabled(false);
                btFriendOption7.setVisible(false);
                btFriendOption7.setEnabled(false);
            case 7:
                friendLabel8.setVisible(false);
                btFriend8.setVisible(false);
                btFriend8.setEnabled(false);
                btFriendOption8.setVisible(false);
                btFriendOption8.setEnabled(false);
            case 8:
                friendLabel9.setVisible(false);
                btFriend9.setVisible(false);
                btFriend9.setEnabled(false);
                btFriendOption9.setVisible(false);
                btFriendOption9.setEnabled(false);
            case 9:
                friendLabel10.setVisible(false);
                btFriend10.setVisible(false);
                btFriend10.setEnabled(false);
                btFriendOption10.setVisible(false);
                btFriendOption10.setEnabled(false);
                break;
        }
    }
    
    private void listBlocked(User toList){
        if(toList.getBlockedList().size() < 5){
            updateBlockedList(toList.getBlockedList().size());
        }
        int i = 0;
        Iterator<User> it = toList.getBlockedList().iterator();
        while(it.hasNext() && i < 5){
            User blocked = it.next();
            switch(i){
                case 0:
                    blLabel1.setVisible(true);
                    blLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    blNameLabel1.setVisible(true);
                    blNameLabel1.setText(blocked.getName());
                    btUnblock1.setVisible(true);
                    btUnblock1.setEnabled(true);
                    break;
                case 1:
                    blLabel2.setVisible(true);
                    blLabel2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    blNameLabel2.setVisible(true);
                    blNameLabel2.setText(blocked.getName());
                    btUnblock2.setVisible(true);
                    btUnblock2.setEnabled(true);
                    break;
                case 2:
                    blLabel3.setVisible(true);
                    blLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    blNameLabel3.setVisible(true);
                    blNameLabel3.setText(blocked.getName());
                    btUnblock3.setVisible(true);
                    btUnblock3.setEnabled(true);
                    break;
                case 3:
                    blLabel4.setVisible(true);
                    blLabel4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    blNameLabel4.setVisible(true);
                    blNameLabel4.setText(blocked.getName());
                    btUnblock4.setVisible(true);
                    btUnblock4.setEnabled(true);
                    break;
                case 4:
                    blLabel5.setVisible(true);
                    blLabel5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_profile.png")).getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
                    blNameLabel5.setVisible(true);
                    blNameLabel5.setText(blocked.getName());
                    btUnblock5.setVisible(true);
                    btUnblock5.setEnabled(true);
                    break;
            }
            i++;
        }
    }
    
    private void updateBlockedList(int size){
        switch(size){
            case 0:
                blLabel1.setVisible(false);
                blNameLabel1.setVisible(false);
                btUnblock1.setVisible(false);
                btUnblock1.setEnabled(false);
            case 1:
                blLabel2.setVisible(false);
                blNameLabel2.setVisible(false);
                btUnblock2.setVisible(false);
                btUnblock2.setEnabled(false);
            case 2:
                blLabel3.setVisible(false);
                blNameLabel3.setVisible(false);
                btUnblock3.setVisible(false);
                btUnblock3.setEnabled(false);
            case 3:
                blLabel3.setVisible(false);
                blNameLabel3.setVisible(false);
                btUnblock3.setVisible(false);
                btUnblock3.setEnabled(false);
            case 4:
                blLabel3.setVisible(false);
                blNameLabel3.setVisible(false);
                btUnblock3.setVisible(false);
                btUnblock3.setEnabled(false);
                break;
        }
    }
    
    public void updateAndListFriendPanel(User toList){
        listFriend(toList);
        listFriendRequest(toList);
        listBlocked(toList);
        if(toList.getFriendRequestList().size() > 0){
            btBuddies.setText(Constants.BT_BUDDIES_TEXT + " ("+ toList.getFriendRequestList().size() + ")");
        } else {
            btBuddies.setText(Constants.BT_BUDDIES_TEXT);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WatchEye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WatchEye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WatchEye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WatchEye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            WatchEye client = new WatchEye();
            LoginServer.getInstance().setClient(client);
            client.setVisible(true);
        });
    }

    public JPanel getLoginScreen(){
        return loginScreen;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blLabel1;
    private javax.swing.JLabel blLabel2;
    private javax.swing.JLabel blLabel3;
    private javax.swing.JLabel blLabel4;
    private javax.swing.JLabel blLabel5;
    private javax.swing.JLabel blNameLabel1;
    private javax.swing.JLabel blNameLabel2;
    private javax.swing.JLabel blNameLabel3;
    private javax.swing.JLabel blNameLabel4;
    private javax.swing.JLabel blNameLabel5;
    private javax.swing.JLabel blockedListLabel;
    private javax.swing.JButton btAccept1;
    private javax.swing.JButton btAccept2;
    private javax.swing.JButton btAccept3;
    private javax.swing.JButton btAccept4;
    private javax.swing.JButton btAccept5;
    private javax.swing.JButton btBlockNext;
    private javax.swing.JButton btBlockPrev;
    private javax.swing.JButton btBuddies;
    private javax.swing.JButton btDecline1;
    private javax.swing.JButton btDecline2;
    private javax.swing.JButton btDecline3;
    private javax.swing.JButton btDecline4;
    private javax.swing.JButton btDecline5;
    private javax.swing.JButton btEnter;
    private javax.swing.JButton btFriend1;
    private javax.swing.JButton btFriend10;
    private javax.swing.JButton btFriend2;
    private javax.swing.JButton btFriend3;
    private javax.swing.JButton btFriend4;
    private javax.swing.JButton btFriend5;
    private javax.swing.JButton btFriend6;
    private javax.swing.JButton btFriend7;
    private javax.swing.JButton btFriend8;
    private javax.swing.JButton btFriend9;
    private javax.swing.JButton btFriendNext;
    private javax.swing.JButton btFriendOption1;
    private javax.swing.JButton btFriendOption10;
    private javax.swing.JButton btFriendOption2;
    private javax.swing.JButton btFriendOption3;
    private javax.swing.JButton btFriendOption4;
    private javax.swing.JButton btFriendOption5;
    private javax.swing.JButton btFriendOption6;
    private javax.swing.JButton btFriendOption7;
    private javax.swing.JButton btFriendOption8;
    private javax.swing.JButton btFriendOption9;
    private javax.swing.JButton btFriendPrev;
    private javax.swing.JButton btGroups;
    private javax.swing.JButton btLoginRegister;
    private javax.swing.JButton btLogoff;
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btRequestNext;
    private javax.swing.JButton btRequestPrev;
    private javax.swing.JButton btResetPassword;
    private javax.swing.JButton btReturn;
    private javax.swing.JButton btSend;
    private javax.swing.JButton btUnblock1;
    private javax.swing.JButton btUnblock2;
    private javax.swing.JButton btUnblock3;
    private javax.swing.JButton btUnblock4;
    private javax.swing.JButton btUnblock5;
    private javax.swing.JComboBox<String> ddBox;
    private javax.swing.JLabel frLabel1;
    private javax.swing.JLabel frLabel2;
    private javax.swing.JLabel frLabel3;
    private javax.swing.JLabel frLabel4;
    private javax.swing.JLabel frLabel5;
    private javax.swing.JLabel frNameLabel1;
    private javax.swing.JLabel frNameLabel2;
    private javax.swing.JLabel frNameLabel3;
    private javax.swing.JLabel frNameLabel4;
    private javax.swing.JLabel frNameLabel5;
    private javax.swing.JLabel friendLabel1;
    private javax.swing.JLabel friendLabel10;
    private javax.swing.JLabel friendLabel2;
    private javax.swing.JLabel friendLabel3;
    private javax.swing.JLabel friendLabel4;
    private javax.swing.JLabel friendLabel5;
    private javax.swing.JLabel friendLabel6;
    private javax.swing.JLabel friendLabel7;
    private javax.swing.JLabel friendLabel8;
    private javax.swing.JLabel friendLabel9;
    private javax.swing.JLabel friendListLabel;
    private javax.swing.JPanel friendPanel;
    private javax.swing.JLabel friendRequestListLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel homeScreen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginFootnote;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JTextField loginMailField;
    private javax.swing.JLabel loginMailLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginPasslLabel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JComboBox<String> mmBox;
    private javax.swing.JTextField newFriendField;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel regDobLabel;
    private javax.swing.JLabel regFootnote;
    private javax.swing.JComboBox<String> regGenderBox;
    private javax.swing.JLabel regGenderLabel;
    private javax.swing.JLabel regHeader;
    private javax.swing.JTextField regMailField;
    private javax.swing.JLabel regMailLabel;
    private javax.swing.JTextField regNameField;
    private javax.swing.JLabel regNameLabel;
    private javax.swing.JLabel regPassLabel;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JCheckBox tosCheckBox;
    private javax.swing.JLabel welcomeLogo;
    private javax.swing.JComboBox<String> yyyyBox;
    // End of variables declaration//GEN-END:variables
}
